version: "3.7"
services:
  node:
    container_name: mitra-frontend-node
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    environment:
      BACKEND_URL: https://mitra-social.herokuapp.com
    extra_hosts:
      - "mitra-backend:172.17.0.1"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"
